#!/bin/bash

export PATH="${PATH}:${HOME}/.local/bin/"

swww init

    swww img /home/caber/.config/hypr/Wallpapers/eclipse.jpg --transition-type grow --transition-fps 60 --transition-duration 1.0 --transition-pos 0.810,0.972 --transition-bezier 0.65,0,0.35,1 --transition-step 255

fi
